### ISSUE TITLE
Mimick does not seem to work on Ubuntu 24.04 aarch64

### ISSUE THREAD

**Issue by clalancette** [ros2/Mimick#35]
When trying to run Mimick on Ubuntu 24.04 aarch64, it fails to start up.

Steps to reproduce:

1.  Clone this repository: `git clone https://github.com/ros2/Mimick`
2.  `cd Mimick`
3. `mkdir build`
4. `cd build`
5. `cmake ..`
6. `make`
7. `./sample/strdup/strdup_test`

That last step will print something like:
```
mimick: Initialization error: could not find definitions for vital function(s): 'abort' 'vfprintf'
Aborted (core dumped)
```

A few other notes:
* Running this test on Ubuntu 22.04 aarch64 works fine.
* Running this test on Ubuntu 24.04 amd64 works fine.
* This failure seems to have something to do with glibc (which happens to be version 2.39 in Ubuntu 24.40).  In particular, Mimick is expecting that there is an exported symbol called `_r_debug` in glibc that contains the symbols for things like `abort` and `vfprintf`.  That symbol does indeed exist, but it seems not to contain the symbols Mimick wants.

**Comment by wjwwood** [comment]
Closed by https://github.com/ros2/Mimick/pull/36
